import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

// ✅ START SCHEDULER INSIDE NEXT.JS
import { startScheduler } from "@/lib/scheduler"

// ✅ INIT WHATSAPP ONCE FOR ENTIRE APP
import { initWhatsApp } from "@/lib/whatsapp"

// 🔒 make sure scheduler starts only once
startScheduler()

// 🔒 start WhatsApp only once (shared by scheduler + UI)
initWhatsApp()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}